### ISSUE TITLE
Configure dccvalidator for CSBC/PS-ON vocabulary

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#1]
The goal is to use [**dccvalidator**](https://github.com/Sage-Bionetworks/dccvalidator) as part of some sort of automated/scheduled process to validate and identify errors in the CSBC/PS-ON metadata, according to specified schemas and vocabularies.

The CSBC/PS-ON controlled vocabulary is currently encoded in this [**Google Sheet**](https://docs.google.com/spreadsheets/d/1_Ho4tjgdxSHo19qFhlLJhZAyQSPPDW-W8JN910GizDs/edit) — which is nice, but doesn't easily allow for automation. While transforming this sheet into a schema based on JSON-LD or JSON Schema might be a long term solution, the current implementation of **dccvalidator** expects a specific format of metadata templates in Excel spreadsheet files.

To get started:
+ Review the vignette on [customizing **dccvalidator**](https://sage-bionetworks.github.io/dccvalidator/articles/customizing-dccvalidator.html); it's probably worth reviewing other vignettes for general usage as well
+ As noted in the vignette, part of this task will involve updating a local copy of the [`config.yml`](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/config.yml) file to point to the appropriate templates and define any project-specific options
+ We also want to get a sense of what inputs and outputs are supported by **dccvalidator**, and where these various pieces need to be stored

Again, we want to automate this process as much as possible. As such, we'll need to develop some scripts (preferably in Python or R) that handle the following steps:
+ Use Google Sheets API client (e.g., [`googlesheets`](https://cran.r-project.org/web/packages/googlesheets/vignettes/basic-usage.html) for R) to pull controlled vocabulary sheets into local dataframes
+ Transform dataframes to match expected [metadata template](https://www.synapse.org/#!Synapse:syn18512044) format (I think the `_manifest` template is probably most relevant, but might be worth checking out the others)
+ Run **dccvalidator** with reformatted templates to validate annotations in CSBC/PS-ON File Views

Once we get everything working, we can set up scheduled jobs (e.g. with TravisCI) to run the validation process on a regular interval.

**Comment by jaeddy** [comment]
@milen-sage does this sound like a reasonable approach? Let me know if there's anything you think would be worth doing differently.

**Comment by milen-sage** [comment]
Yes, this sounds great!

pygsheets is a package for python that could be useful for interfacing with google sheets as well.

**Comment by vpchung** [comment]
Sorry, late update!

I was able to generate two template files (template_datasets.xlsx and template_publications.xlsx), as well as reduce the aforementioned Google sheet into a single TSV file ~~, which are all currently living in my own Synapse project.  Would it be okay if they live in the [CSBC-PSON project](https://www.synapse.org/#!Synapse:syn21498902/wiki/600349) instead?~~
**EDIT: the templates and annotations now live in our CSBC-PSON Portal DB project!**

Currently, our version of the dccvalidator tool can validate files when run from the command-line. My next plan of action is to have it validate files/tables already on Synapse.

**Comment by vpchung** [comment]
A [CSBC/PS-ON curator app](https://shinypro.synapse.org/users/vchung/csbc-pson-manifest/) (which utilizes dccvalidator functions) have been developed, so I'm going to close this!
