### ISSUE TITLE
add parsing of dbGaP and SRA to pubmed crawler

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#10]
@vpchung would you please add functionality to the pubmed crawler that will parse out links to dbGaP studies and SRA studies (not individual samples) much as we do for GEO datasets?

Here is how I would do this manually:
SRA, dbGaP, and GEO links should be provided under Related information section on the right side of PubMed site (under subheadings “SRA”, “dbGaP”, and “GEO DataSets”, respectively). E.g., for the publication:
https://www.ncbi.nlm.nih.gov/pubmed/?term=27146274

For SRA: we want a link to study (identified via an “SRP” identifier). To get this, click on the SRA link (https://www.ncbi.nlm.nih.gov/sra?LinkName=pubmed_sra&from_uid=27146274 in this example), click on the first item in the list (https://www.ncbi.nlm.nih.gov/sra/SRX1590618[accn] in this example), and finally find the SRP number listed under study (SRP070460 in this example and use the associated link:
https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP070460).
Is there a more direct way of finding this SRP? 

For dbGaP: We want a link to the sudy. To get this, click on the dbGaP link (https://www.ncbi.nlm.nih.gov/gap/?LinkName=pubmed_gap&from_uid=27146274 in this example) and find the study identifier(s) listed in the table. In this example, the study accession link is https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001231.v2.p1.

For GEO: We want a link to the GSE. Click on the GEO Datasets (https://www.ncbi.nlm.nih.gov/gds?LinkName=pubmed_gds&from_uid=27146274, in this example). We want each link listed here. In this example, there is only one: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE78036.

**Comment by vpchung** [comment]
Sorry, late update!

This request has been completed by #12.
