### ISSUE TITLE
Greek letters in publication title will not redirect to its "card" correctly

### ISSUE THREAD

**Issue by vpchung** [mc2-center/csbc-pson-dcc#101]
I'm not sure if this is the appropriate place to address this issue, but I noticed this publication:

<img width="906" alt="Screen Shot 2021-03-24 at 5 50 58 PM" src="https://user-images.githubusercontent.com/9377970/112403850-6f181b80-8ccc-11eb-9158-a0a539e02cfd.png">

will not open correctly on the portal. Judging from the query parameter in the URL, I'm assuming this is from the alpha character in the title:

<img width="1022" alt="Screen Shot 2021-03-24 at 6 13 47 PM" src="https://user-images.githubusercontent.com/9377970/112403984-b6061100-8ccc-11eb-9b90-810f8a69a9b2.png">

@jaeddy Should I simply have the curator app change all Greek letters to their respective names?

**Comment by jaeddy** [comment]
Hmm... I'll see if there's a way to fix this in the portal config (e.g., maybe we can key the link query on `pubMedId` instead of `publicationTitle`).

**Comment by vpchung** [comment]
I think pubMedId would make for a cleaner URL as well!

**Comment by vpchung** [comment]
@jaeddy I saw in the [JIRA ticket](https://sagebionetworks.jira.com/browse/PORTALS-1883) that you are proposing using `publicationId` as the query parameter instead of `publicationTitle`.

I agree that using `publicationId` will be better than `publicationTitle` -- plus it'll be consistent with how the dataset cards are queried, since they use `datasetId`.  The only concern I have is that I had updated the curator app so that it would not create new File entities for publications; instead, it would just create a new row in the Portals - Publication Merged table.  Should I re-add that entity creation step?  Otherwise, we will probably run into the same issue as above, in that a card will not properly display for the new publications (since there's no associating `publicationId`).

**Comment by jaeddy** [comment]
Oh, crap - you're right. I forgot about that. I think we can just use `pubMedId` for now then (assuming we still annotate that for everything), and maybe switch to `publicationId` later. Can you chime in on the Jira ticket to clarify?

**Comment by vpchung** [comment]
@jaeddy done!

**Comment by vpchung** [comment]
@jaeddy Following up on the discussion from the JIRA ticket, would it be appropriate to just replace the `publicationTitle` column with `pubMedId`?  Or do we explicitly need `publicationTitle` in the schemas for Datasets and Tools?

(I did look back at our CSBC/PS-ON data model diagram, but I can't really tell which column is acting as the foreign key between publications and datasets/tools.  I'm hoping that means we can just change what we use as the FK?)
