### ISSUE TITLE
Update column types in merged tables

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#103]
There are a number of columns for which we should try to update types in the "merged" tables that drive CCKP. In most cases, the conversion is from a single value type to a `_LIST` type (which would also involve splitting a delimited string into a JSON array) — e.g.:

<details>
<summary><code>.delim_str_to_json()</code></summary>
<pre>
<code>
.delim_str_to_json <- function(str, delimiter = ",") {
  json_str <- str_split(str, delimiter)[[1]] %>%
    str_trim() %>%
    jsonlite::toJSON()
  if (json_str == "[null]" || json_str == '[""]') {
    ""
  } else {
    json_str
  }
}
</code>
</pre>
</details>

There are also a number of cases where we'd ideally use lists of entity IDs (`ENTITYID_LIST`), but this might not be possible through any of the clients right now. I was hoping this would be a simple fix, but I had it ended up being a more time consuming task (for me at least). @thomasyu888 or @andrewelamb (or anyone) — could you take a look at this?

- [ ] [**Publications**](https://www.synapse.org/#!Synapse:syn21868591/tables/)
  - [ ] `themeId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `consortiumId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `datasetId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `dataset`: `STRING` -> `STRING_LIST`
- [ ] [**Tools**](https://www.synapse.org/#!Synapse:syn21930566/tables/)
  - [ ] `themeId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `consortiumId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `consortium`: `STRING` -> `STRING_LIST`
  - [ ] `grantId`: `STRING_LIST` -> `ENTITYID_LIST` (if possible)
  - [ ] `publicationId`: `STRING_LIST` -> `ENTITYID_LIST` (if possible)
- [ ] [**Datasets**](https://www.synapse.org/#!Synapse:syn21897968/tables/)
  - [ ] `themeId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `consortiumId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `grantId`: `STRING_LIST` -> `ENTITYID_LIST` (if possible)
  - [ ] `publicationId`: `STRING_LIST` -> `ENTITYID_LIST` (if possible)
- [ ] [**Grants**](https://www.synapse.org/#!Synapse:syn21918972/tables/)
  - [ ] `themeId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `consortiumId`: `STRING` -> `ENTITYID_LIST` (`STRING_LIST` OK)
  - [ ] `consortium`: `STRING` -> `STRING_LIST`

**Comment by vpchung** [comment]
Closing, as we are no longer using `*Id` columns.
