### ISSUE TITLE
Deprecate old/unused tables

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#13]
We should clean up some of the [**Tables and Views**](https://www.synapse.org/#!Synapse:syn7080714/tables/) in Synapse — mostly for our own sanity. @bswhite, @milen-sage, @vpchung can you take a look and confirm whether these are safe to remove?

+ **`CSBC and PSON Project Information Integration`** ([syn11968325](https://www.synapse.org/#!Synapse:syn11968325/tables/)): pretty sure this hasn't been used since the 2018 site visit 
+ **`metadata schema`** ([syn8703113](https://www.synapse.org/#!Synapse:syn8703113/tables/)): not sure if this has ever been used...
+ **`Publications staging`** ([syn20938140](https://www.synapse.org/#!Synapse:syn20938140/tables/)): seems like a temporary thing?
+ **`Tool and Algorithm Catalog`** ([syn11380099](https://www.synapse.org/#!Synapse:syn11380099/tables/)): replaced by `Portal - Tools`?
+ **`Study Table`** ([syn21517424](https://www.synapse.org/#!Synapse:syn21517424/tables/)): are we still using "studies" for anything? 
+ **`Study View`** ([syn18483791](https://www.synapse.org/#!Synapse:syn18483791/tables/)): folders annotated as `is.study` — probably not needed anymore 
+ **`CSBC and PSON Studies and Experiments`** ([syn10915872](https://www.synapse.org/#!Synapse:syn10915872/tables/)): not really sure what this is...

**Comment by vpchung** [comment]
I'm not sure about the others, but `Publications staging` should be safe to remove (but we should confirm with @bswhite and @milen-sage just in case). It was originally used to house all the newly scraped publications before merging them into the `Publications` table.

But I've since changed the PubMed crawler to output to a CSV file instead.

**Comment by milen-sage** [comment]
All are safe to remove from my point of view, though I see @bswhite has updated study table in Jan this year.

The last time I used 'CSBC and PSON Studies and Experiments' (https://www.synapse.org/#!Synapse:syn10915872/tables/) Sara wanted me to add scRNA-seq datasets from studies across CSBC and PSON. But I think all datasets are now reflected elsewhere.

**Comment by jaeddy** [comment]
Instead of deleting, I moved tables and views to a separate project: [**CSBC PS-ON Archive**](https://www.synapse.org/#!Synapse:syn11968325/tables/).
