### ISSUE TITLE
id columns that could be added to the various merged tables

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#25]
The merged tables need id columns of entities to help with the reverse ETL process.

- [x] Grants:
consortium, institution, ~~person(investigator)~~, theme

- [x] Projects:
project, grant, theme, consortium

- [x] Datasets:
consortium, grant

- [x] Publications:
grant, theme, consortium

- [x] Tools:
theme, consortium

**Comment by jaeddy** [comment]
@andrewelamb should be done (finally). Let me know if you think I missed any!
