### ISSUE TITLE
Fix NAs / unannotated values

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#27]
Replace all `"NA"` strings with `""` so they don't show up in the portal. Figure out what to do about `"Not Applicable"` (and `"Unspecified"`, `"Unannotated"`?) values. Make sure that non-string empties (e.g., integer for `publicationYear`) are also handled correctly. Figure out how to get Synapse to recognize "Not set" for list type columns.

**Comment by bswhite** [comment]
@jaeddy do you know where "Not set" comes from? e.g. ,I'm surprised to see publications with assay "Not set." "Not Applicable" makes sense, but Julie or I should have filled in any blanks/unset values. I can look into this further if you didn't introduce "Not set"

**Comment by jaeddy** [comment]
"Not set" is automatically displayed by Synapse (the web client) for empty facet values.

As for missing assays on publications, that sounds more like an error that I might have introduced... I can take a closer look.

**Comment by jaeddy** [comment]
@bswhite any thoughts on `"Unspecified"`, `"Unannotated"`, etc.? Sounds like we want to keep `"Not Applicable"`?

**Comment by bswhite** [comment]
I have a slight preference for "Unspecified" (over "Unannotated") indicating that we attempted to annotate this, but could not.

I think "Not Applicable" should be "", so they don't show up in the cards (and hopefully eventually not in the pie charts and facets).

Using "" will create an issue differentially between "Not Applicable" and "Not Yet Annotated." I think we should just try to catch those as we go through manually. In the future, when we add things without annotations (the shame!) we should use "NA" or "NULL" -- something we can easily find and fill in.

Not ideal ... I'm open to other suggestions.

**Comment by jaeddy** [comment]
Got it — I'll make another pass to include those changes.

When we have the end-to-end pipeline working a bit better, we can keep the "Not Yet Annotated" in the internal tables for our own information/tracking — then remove them from the tables that get shown in the portal.

**Comment by jaeddy** [comment]
Calling this fixed for now.

**Comment by jaeddy** [comment]
There are a few straightforward issues with some of the CSBC to address, and some more complicated:

### 1. Single element lists with an empty string (e.g., `[""]`):

(FYI @jay-hodgson - figured out what seems to be happening)

In Synapse, this renders as such in the facet selection menu:
![image](https://user-images.githubusercontent.com/5033229/106088149-3bf54980-60da-11eb-80a7-33d2bf5db9f8.png)

The Synapse React Client also gets confused in portals:
![image](https://user-images.githubusercontent.com/5033229/106088285-8c6ca700-60da-11eb-8480-640c059aa2c0.png)

Values in the same column that render (correctly) as `Not set` show up in R as `NA`s. So, at least for list columns, we should replace `[""]` instances with `NA`. Note: I can't remember it's canonical for _non-_list columns to replace `""` instances with `NA`. Maybe @allaway or @kelshmo can remind me of the preferred approach?

### 2. Lost "Not Applicable" values:

In this [`portal_cleanup.Rmd` notebook](https://github.com/Sage-Bionetworks/csbc-pson-dcc/blob/etl-debugging/nbs/portal_cleanup.Rmd), which I conveniently never merged to develop, it looks like I'm explicitly replacing `Not Applicable` with `NA`... which seems counter to [this comment](https://github.com/Sage-Bionetworks/csbc-pson-dcc/issues/27#issuecomment-625988824) above.

I think we can recover these `Not Applicable` values (which have actual meaning) from tables like [this one](https://www.synapse.org/#!Synapse:syn21795742/tables/) and others, but it might require a bit more work (and certainly a bit more care to ensure we don't overwrite newer data).

### 3. Unannotated values that aren't up to date?

For publications, datasets, and tools that have been annotated by Rancho Biosciences (or investigators), it seems like we have a smaller fraction of missing annotations. Maybe we could concatenate the various manifests they've used into a single table for each resource type, and use that to spot check for inconsistencies (cc @vpchung).

### 4. Unknown unknowns...

For everything that's left, we'd ideally want to do a more thorough review and provide concrete values for "missing" annotations — e.g., `Not Applicable` (when the field isn't applicable to the particular entity) and `Unspecified` (when the value for the field could not be determined for the entity).

**Comment by vpchung** [comment]
> So, at least for list columns, we should replace [""] instances with NA

@jaeddy @brynnz22 I have made this change in the curator app, but some cleaning of the existing `[""]` annotations in the **Portal - * Merged** will probably be needed.  I should also say that I have no idea if my fix will even work as expected...... 😅 

e.g. the "assay" annotation is a `StringList` column type, so would something like this work?

```R
dataset_row <- function(syn_id, manifest) {
  assay <- NA
  ...
}
```
