### ISSUE TITLE
Discrepencies between portalETL results and merged table for projects

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#32]
These projects don't have grants:

# A tibble: 7 x 2
  projectId   projectName                                                                                         
  <chr>       <chr>                                                                                               
1 syn21917484 Identification of personalized adaptive response mechanisms in breast cancer by information theory …
2 syn21917485 Predictive Modeling of the EGFR-MAPK pathway for Triple Negative Breast Cancer Patients             
3 syn21917486 Reverse Sensitivity Analysis for Identifying Predictive Proteomics Signatures of Cancer             
4 syn21917487 Optimal control models of epithelial-mesenchymal transition for the design of pancreas cancer combi…
5 syn21917488 Integrated mathematical and experimental analysis of immune system signaling in breast cancer       
6 syn21917489 Systems analysis of aggressive prostate cancer pathology                                            
7 syn21917490 Single-cell characterization of tumor and microenvironment coevolution in Peripheral T-cell Lymphom

Should they remain in the normalized tables?

The merged project table(syn21868602) has 96 rows in it, the project table(syn21645147) has 136 rows in it. 7 of those should be the above grantless projects, but there are still projects that should be in the merged table? Perhaps the projects table was updated, and the merged tables have not?

**Comment by bswhite** [comment]
These are all new U01 grants. There was some inconsistency (e.g., there might have been projects defined but not their grants) that I resolved immediately before the site visit by directly editing the merged tables.

Below I describe the links between the above projects and their grants. All of the associated metadata should be in the snapshot of the grants table I took before the site visit (syn21981384) and in the projects snapshot (syn21981383).

1. This belongs to grantId = syn21619070; grantNumber = CA238720; grantName = Identification of personalized adaptive response mechanisms in breast cancer by information theory and proteomics

2. This belongs to grantId = syn21619853; grantNumber = CA238475; grantName = Predictive Modeling of the EGFR-MAPK pathway for Triple Negative Breast Cancer Patients

3. This belongs to grantId = syn21619759; grantNumber = CA227544; grantName = Reverse Sensitivity Analysis for Identifying Predictive Proteomics Signatures of Cancer

4. This belongs to grantId = syn21619432; grantNumber = CA243007; grantName = Optimal control models of epithelial-mesenchymal transition for the design of pancreas cancer combination therapy

5. This belongs to grantId = syn21619082; grantNumber = CA232216; grantName = Integrated mathematical and experimental analysis of immune system signaling in breast cancer

6. This belongs to grantId = syn20673545; grantNumber = CA231978; grantName = Systems analysis of aggressive prostate cancer pathology

7. This belongs to grantId = syn21619773; grantNumber = CA243073; grantName = Single-cell characterization of tumor and microenvironment coevolution in Peripheral T-cell Lymphomas

**Comment by jaeddy** [comment]
@bswhite - I don't have access to any of the grant Synapse projects except (6). Can you update the sharing settings?

Otherwise, I've filled in the `grantId` annotation for each of these projects, so can close this issue after confirming that the links are valid.

**Comment by bswhite** [comment]
@jaeddy you should have access now through "CSBC PSON Administrators" -- which I've just ensured has admin access to all the grants. This was generally true of older grants and generally not true of newer grants. Let me know if there is something you still can't access.

**Comment by jaeddy** [comment]
These should all be fixed in the [merged projects table](https://www.synapse.org/#!Synapse:syn21868602/tables/) now.
