### ISSUE TITLE
Use grantNumber as key for grants not grantName

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#34]
Grant Names should not be used as keys. They are unwieldy, but they also sometimes change. Probably they shouldn't -- I suspect we are just sometimes creating temporary names for a grant before we know it's official name. For example:

syn9775665 CSBC U01 Project Boston University is grant CA182898. It has been renamed:
Uncoupling obesity from breast cancer in African American women. This renaming has created inconsistencies.

Maybe a better motivator is typos. e.g., grant CA217655 was originally assigned grantName "Steady States and Cellular Transitions Associated with Carcinogenesis and Tumorprogression" (notice the typo/lack of space between "Tumor" and "progression"). When I fixed this, I again created inconsistencies.

**Comment by jaeddy** [comment]
@bswhite - I've updated all tables to facet on grant number instead of name. The change propagated to the staging site without needing to modify any of the portal configs.

**Note:** I haven't updated any of the card configs to ensure that queries (i.e., to direct links to the correct "details" page) are keyed on `grantNumber` instead of `grantName`. That step aside, do we want to use grant number for _display_ for facets and charts?

**Comment by bswhite** [comment]
@jaeddy nice! I think we should continue to display grantNames not grantNumbers. I know the former are unwieldy, but they are more informative.

**Comment by jaeddy** [comment]
@bswhite I agree that (a) grantNumbers are more stable/reliable as keys, and (b) grantNames are more informative — though neither are particularly useful as facets (both in terms of formatting and information content). What if we kept both in the table for query and/or search, but instead use **"Grant Institution"** as the facet? Curious if @jkcinelli has thoughts.

**Comment by jkcinelli** [comment]
I do agree that "Grant Institution" might be the most useful facet.

**Comment by jaeddy** [comment]
👍 I'll try it out with one of the tables and we can evaluate.

**Comment by bswhite** [comment]
I can see value in both grant institution and grant name. But, if I had to choose one, I would stick with grant name. institution won't be unique -- there are a lot of mit grants, a lot of columbia grants. On the flip side (or argument for both), while some grant names clearly indicate the (single) institution, others are very generic -- and unless you know to be searching for that grant name (and sometimes you would), it won't be informative.

I faceted quite a bit using grantName while preparing for the site visit. I didn't find the long names overly obnoxious.

**Comment by jaeddy** [comment]
Fair point. I think lack of uniqueness would generally be an argument in favor of any particular field being a facet (i.e., more like a categorical variable for selecting/subsetting than an identifier). However, the ideal way to handle something like `grantName` would probably be more of a text field with look-ahead / auto-complete — e.g.,

![image](https://user-images.githubusercontent.com/5033229/81863642-638e8c80-9520-11ea-9295-e9d697a06194.png)

... and we obviously don't have the option to do that currently. I think keeping both name and institution as facets is probably the move for now.
