### ISSUE TITLE
Represent different representations (e.g., GEO, SRA, dbGaP) of the same data as a single dataset with BioProject identifier

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#35]
We decided to have a single dataset that includes different representations of a file/sample across GEO, SRA, dbgap, synapse, etc.

We currently have a separate dataset portal object/card for a GEO GSE and an SRA SRP that have the same title / dataset name and refer to the same underlying raw data.
When GSE and SRA datasets are paired, a dataset is getting created for both:
SELECT * FROM syn21897968 WHERE ( "datasetAlias" = 'GSE116011')
SELECT * FROM syn21897968 WHERE ( "datasetAlias" = 'SRP150876')

Both of these have name
"An Optically Decodable Bead Array for Linking Imaging and Sequencing with Single-Cell Resolution"
as you can see on GEO
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE116011
and SRA:
https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP150876

We agreed to use the BioProject id: PRJNA476792
https://www.ncbi.nlm.nih.gov/bioproject/PRJNA476792

Does this exist for all cases where we have multiple representations of the data? How can we map GSE ids, SRP ids (and eventually dbgap Ids) to BioProject ids?

**Comment by bswhite** [comment]
Here is my plan to do this:

For any set of datasets having the same datasetName, at least one of which is a GSE/GEO dataset
e.g., 
SELECT * FROM syn21897968 where "datasetName" = 'An Optically Decodable Bead Array for Linking Imaging and Sequencing with Single-Cell Resolution'

https://www.synapse.org/#!Synapse:syn21897968/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxODk3OTY4IHdoZXJlIFwiZGF0YXNldE5hbWVcIiA9ICdBbiBPcHRpY2FsbHkgRGVjb2RhYmxlIEJlYWQgQXJyYXkgZm9yIExpbmtpbmcgSW1hZ2luZyBhbmQgU2VxdWVuY2luZyB3aXRoIFNpbmdsZS1DZWxsIFJlc29sdXRpb24nIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==

Do the following:

1. Concatenate the externalLink fields across the set. For example:
[GEO:GSE116011](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE116011),
[SRA:SRP150876](https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP150876)
2. Add a new field externalLinkIds:
GSE116011, SRP150876
3. Only keep the single GSE dataset (here GSE116011)
4. Set its alias to the corresponding BioProject (i.e., PRJNA476792)
5. Change its datasetId to be the folder with its data (e.g., under /files/datasets/GSE116011 for the above). This can be found by searching under the grant's /files/datasets.
https://www.synapse.org/#!Synapse:syn21811287
6. Change the name of this dataset folder to be the BioProject id (PRJNA476792)
7. Fix the associated publication to point to this one dataset only
i.e., fix the datasetId to be the folder in (6) and set the dataset to be the BioProject id (PRJNA476792)
SELECT * FROM syn21868591 where "publicationTitle" = 'SCOPE-Seq: a scalable technology for linking live cell imaging and single-cell RNA sequencing'
https://www.synapse.org/#!Synapse:syn21868591/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxODY4NTkxIHdoZXJlIFwicHVibGljYXRpb25UaXRsZVwiID0gJ1NDT1BFLVNlcTogYSBzY2FsYWJsZSB0ZWNobm9sb2d5IGZvciBsaW5raW5nIGxpdmUgY2VsbCBpbWFnaW5nIGFuZCBzaW5nbGUtY2VsbCBSTkEgc2VxdWVuY2luZyciLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9
8. Need to change the datasetId, datasetName, and datasets annotations of all files associated with this dataset to have the new name (PRJNA476792). I'm being lazy -- probably all three of these annotations don't need to be changed.

**Comment by jaeddy** [comment]
@bswhite this is looking pretty good in the merged table — would you say it's done? Let me know if you need help with anything.

**Comment by bswhite** [comment]
Yep, it's done.
