### ISSUE TITLE
finding BioProject associated with a GEO GSE id

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#38]
You can look up a BioProject associated with a GEO GSE id using rentrez:

library(rentrez)
r_search <- entrez_search(db="bioproject", term="GSE116011")
r_search$ids  ## Ideally, just one
## [1] "476792"

entrez_summary(db="bioproject", r_search$ids[1])$project_acc

**Comment by bswhite** [comment]
library(rentrez)
lookup.gse <- function(gse) {
    r_search <- entrez_search(db="bioproject", term=paste0(gse, "[BPRJ]"))
    r_search$ids
}

get.gse.bioproject <- function(gse) {
    ids <- lookup.gse(gse)
    if(length(ids) != 1) { stop("Got multiple ids\n") }
    entrez_summary(db="bioproject", id=ids)$project_acc
}

## > get.gse.bioproject("GSE133747")
## [1] "PRJNA552370"

**Comment by jaeddy** [comment]
For the `entrez_search` term, I figured out that adding ` NOT superseries[Relevance]` can be helpful for avoiding multiple matches — i.e., a GSE ID should only be associated with one BioProject, unless one of those BioProjects represents a "super series".

**Comment by bswhite** [comment]
And the reverse search:
r_search <- entrez_search(db="gds", term="PRJNA429917[ACCN]")
entrez_summary(db="gds", id=r_search$ids)$accession
[1] "GSE109171"

**Comment by jaeddy** [comment]
@bswhite I copied this to a [wiki page](https://github.com/Sage-Bionetworks/csbc-pson-dcc/wiki/NCBI-API-Usage) to keep as a reference.
