### ISSUE TITLE
rows in merged dataset table have theme values while missign theme ids

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#39]
https://www.synapse.org/#!Synapse:syn21897968/tables/

This dataset for example:

[Glioblastoma Data](https://www.synapse.org/#!Synapse:syn11510898)

has the theme "heterogeneity/evolution" with an NA in its themeId column.

Any rows like these will lose their themes during any reverse etl process since they have no theme id

**Comment by jaeddy** [comment]
Fixed.
