### ISSUE TITLE
theme, assay, tumorType columns don't exists in dataset table

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#40]
The merged dataset [table](https://www.synapse.org/#!Synapse:syn21897968/tables/) has three columns: theme, assay, tumorType, that don't exist in the normalized dataset [table](https://www.synapse.org/#!Synapse:syn21889931/tables/). These are list columns so association tables will likely need to be added, otherwise manually added value will be lsot durring reverse etl.

**Comment by jaeddy** [comment]
For a few reasons (which I'll try to capture in other issues), I think we'll need a different strategy for datasets. Closing this for now.

**Comment by andrewelamb** [comment]
@jaeddy Should we address this now? My thoughts are to have dataset_assay, dataset_tissue, dataset_tumorType tables in the normalized tables.
