### ISSUE TITLE
remove GEO superseries datasets

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#42]
@jaeddy I would like to remove GEO superseries datasets from curation / the datasets (and pubs) tables. What do you think?

Of the ~330 datasets currently on the portal, 23 are superseries. This reduces the annotation burden somewhat. Also, there essentially stubs with descriptions (taken from GEO) like:
"This SuperSeries is composed of the SubSeries listed below."
We could cobble together the descriptions of the individual datasets. But that's more work -- presumably not difficult to do, but we would have to somehow collect those individual datasets. The hierarchical relationship is also kind of nice -- cohesion between datasets. But that's confusing since we don't do it outside GEO. I think linking related datasets under the same publication is nearly as good an approach -- or maybe between. And simpler.

**Comment by jaeddy** [comment]
I fully support this idea! Even GSE series are a little awkward to treat as "datasets" as GEO has a concept for that (GDS), but the hierarchy is more straightforward/consistent in that case. Maybe at some point we can re-introduce a "parentSeries" annotation (or something similar), but I'm fine excluding for now.

**Comment by bswhite** [comment]
Great. Thanks.

For my future reference, rather than do this programmatically, I used the Synapse UI:

Query for superseries:
SELECT * FROM syn21897968 where "description" LIKE '%SuperSeries%'
and then remove all of the datasets returned by the query.

We will need to be smarter about what GEO datasets go _into_ this table -- as an extreme fallback, if we are about to add a GSE id to a table, we could query its description to see if it contains the word "SuperSeries"
