### ISSUE TITLE
Theme IDs missing from tools in merged tools table

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#44]
These two tools are missing their themeId and themes. The issue is themes are a property of their grant, so this type of edit can't be saved via reverse etl. Either the grantId needs to be changed, or their themes will be added back in each time we run the portalETL process
````
# A tibble: 2 x 5
  toolId      toolName                           grantId    themeId theme
  <chr>       <chr>                              <chr>      <chr>   <chr>
1 syn21645195 p-Creode                           syn9775651 NA      []   
2 syn21645196 Systems biology modeling in Python syn9775651 NA      []  
````

**Comment by jaeddy** [comment]
@andrewelamb do we not have themes associated with that particular `grantId`? That should be something we can fix.

**Comment by jaeddy** [comment]
The answer is apparently "nope". Here's the grant project:
https://www.synapse.org/#!Synapse:syn9775651/wiki/427107

@bswhite any thoughts on how to assign theme(s) here?

**Comment by bswhite** [comment]
@andrewelamb did something change above? I don't see a problem. The grant that James listed (and that is associated with those tools) has Themes
Drug Resistance/Sensitivity, Heterogeneity
with theme Ids:
syn21630076, syn21630075
These are set in the grants table:
SELECT * FROM syn21918972 where "grantId" = 'syn9775651'

**Comment by jaeddy** [comment]
Weird. Not sure what happened... I'll make sure the fix is propagated to the tools table.

**Comment by jaeddy** [comment]
Fixed in merged tools table.
