### ISSUE TITLE
Create link entities for all NCBI samples associated with BioProjects

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#49]
Files like [this one](https://www.synapse.org/#!Synapse:syn21789711) are entities linked to external files on an NCBI ftp server.

![image](https://user-images.githubusercontent.com/5033229/81456375-eab9ba00-9146-11ea-895c-1f9c62ff1c34.png)

As we fill out the table of samples linked to BioProjects (see #53), we should make sure to create and annotate corresponding entities in Synapse.

**Comment by andrewelamb** [comment]
@jaeddy I'm think I'm unclear on what this entails.

Do we want a link entity for every row in [this table](https://www.synapse.org/#!Synapse:syn22015979/tables/)? Are the columns in that table the annotations we want to add to the link entity?

**Comment by milen-sage** [comment]
Tentatively marked as FAIR data. But let's revisit as we are ramping up on crawling work.

**Comment by vpchung** [comment]
Closing, as I don't think we need to create Synapse entities for these anymore.
