### ISSUE TITLE
Update short/display name for institutions

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#50]
I've grabbed standard institution names and aliases from the [Research Organization Registry](https://ror.org/) API. However, not all institutions include an alias / abbreviation / acronym on the site (and some are maybe not great in terms of display).

I'm hoping that we can update the `displayName` column in [this table](https://www.synapse.org/#!Synapse:syn21905891/tables/) to have sensible (and less verbose) representations of all sites that we can use in the portal.

For example...
+ "Columbia University" can probably be denoted as "Columbia" and "Cornell University" as "Cornell", rather than both as "CU"
+ "Dana-Farber Cancer Institute" could be displayed as "Dana-Farber"
+ "Georgia Institute of Technology" might make more sense as "Georgia Tech" than "GT"

**Comment by jkcinelli** [comment]
Completed.
