### ISSUE TITLE
Fill in text for ecosystem section of homepage

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#51]
We need to fill in some actual text for the "Cancer Resource Information Ecosystem" section of the portal homepage.

![image](https://user-images.githubusercontent.com/5033229/81378518-4854f480-90bc-11ea-9809-7251ece8df24.png)

This can be done by editing the sub-wiki pages here:
https://www.synapse.org/#!Synapse:syn21498902/wiki/601488

**Comment by jkcinelli** [comment]
@jaeddy Should we include this under Cloud Platforms: https://datascience.cancer.gov/data-commons

**Comment by jaeddy** [comment]
@jkcinelli my thinking that the CRDC falls into two buckets: the various "data commons" (GDC, PDC, etc.) and the [Cloud Resources](https://datascience.cancer.gov/data-commons/cloud-resources). The latter are more about being able to compute at scale vs. just hosting and exploring data.

**Comment by jaeddy** [comment]
I guess it probably wouldn't hurt to have summary descriptions of the different sections... I'll think about that some more. 🙂

**Comment by jkcinelli** [comment]
Completed. Please let me know if any of these need additional text.
