### ISSUE TITLE
Troubleshoot and run publication-to-sample NCBI data retrieval script

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#53]
The main function, `get_bp_sra_df()` in [this notebook](https://github.com/Sage-Bionetworks/csbc-pson-dcc/blob/master/nbs/ncbi_crawler.Rmd) currently only works for the first 9 BioProject IDs. This is the error for the 10th project:

```
Error in entrez_check(response) : HTTP failure 414, the request is too large. For large requests, try using web history as described in the rentrez tutorial
```

... but I'm guessing that won't be the last. The goal is to debug and run for all 198 (currently) BPs and store the results in [this table](https://www.synapse.org/#!Synapse:syn22015979/tables/).

Assigning to @andrewelamb given the R emphasis, but can switch to @vpchung depending on what you each want to work on!

**Comment by vpchung** [comment]
Sure, let me know what you think, @andrewelamb !

**Comment by bswhite** [comment]
@andrewelamb , I also had difficulty with getGEO bombing on some datasets. I never figured out why, but just skipped over them. When you get to this, let me know which one dies and I can see if I had a similar issue with getGEO.

As usual ... my approach was to get something 90% working on 80% of cases ... to have something to show the NCI.

**Comment by jaeddy** [comment]
I think I sorted out the various snags — NCBI data for 14,196 samples now available in the [`bioproject_sra` table](https://www.synapse.org/#!Synapse:syn22015979/tables/). I'll check the updated code in tomorrow.
