### ISSUE TITLE
Add additional vocabularies to CSBC/PS-ON annotations table

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#54]

**Comment by vpchung** [comment]
@jaeddy Not sure if this is what you meant, but @brynnz22 has uploaded a master list of the CV terms to a Synapse table [here](https://www.synapse.org/#!Synapse:syn25322361/tables/).  She is actively maintaining it and will add terms to it with every Rancho update.

If that's acceptable, I'll go ahead and close this issue!

**Comment by jaeddy** [comment]
That seems like a good bet — I'm not entirely sure what I meant either... 😅 

The updated table looks great! Thanks, @brynnz22 and @vpchung!
