### ISSUE TITLE
link tools to publications in publication card

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#58]
@jaeddy it looks like tools are not linked to publication cards, even though they are on the publication detail page. Do you agree those tool links should be included on the publication card?

e.g., if you search under "publication" (this needs to be changed, but that's another issue) for "viper", you will see this publication:
Quantitative assessment of protein activity in orphan tissues and single cells using the metaVIPER algorithm
The card has a dataset but no tools.
But if you click on the publication title you will be brought to the details page, which includes not only a dataset, but a tool as well. I think that tool should be included on the publication card (and on the top of the details page).

**Comment by jaeddy** [comment]
Hmm.. yeah, that seems perfectly sensible to me. We're treating publications, datasets, and tools are our "trifecta" of resources, so it make sense that we'd have links going in all directions between them.

**Comment by vpchung** [comment]
Closing; linking has been fixed.
