### ISSUE TITLE
Projects missing merged projects table

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#62]
These projects are in the projects table, but missing from the merged projects table:

[1] "syn21645010" "syn21645011" "syn21645016" "syn21645018" "syn21645019" "syn21645022" "syn21645023"
 [8] "syn21645029" "syn21645040" "syn21645045" "syn21645057" "syn21645059" "syn21645065" "syn21645067"
[15] "syn21645068" "syn21645071" "syn21645072" "syn21645075" "syn21645078" "syn21645080" "syn21645081"
[22] "syn21645086" "syn21645087" "syn21645092" "syn21645094" "syn21645100" "syn21645110" "syn21645112"
[29] "syn21645118" "syn21645119" "syn21645124" "syn21645125" "syn21645127" "syn21645129" "syn21645132"
[36] "syn21645134" "syn21645135" "syn21645137" "syn21645139" "syn21645141" "syn21917484" "syn21917485"
[43] "syn21917486" "syn21917487" "syn21917488" "syn21917489" "syn21917490"

**Comment by bswhite** [comment]
@andrewelamb can you give me more information about these projects -- in particular, what are their associated grantIds, grantNumbers, and grantNames? I wonder if I manually removed their associated grants. If you know the project name that would also be helpful.

**Comment by andrewelamb** [comment]
@bswhite @jaeddy 

Here are the relevant [projects](https://www.synapse.org/#!Synapse:syn21645147/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjQ1MTQ3IHdoZXJlIGlkIGluICgnc3luMjE2NDUwMTAnLCAnc3luMjE2NDUwMTEnLCAnc3luMjE2NDUwMTYnLCAnc3luMjE2NDUwMTgnLCAnc3luMjE2NDUwMTknLCAnc3luMjE2NDUwMjInLCAnc3luMjE2NDUwMjMnLCAnc3luMjE2NDUwMjknLCAnc3luMjE2NDUwNDAnLCAnc3luMjE2NDUwNDUnLCAnc3luMjE2NDUwNTcnLCAnc3luMjE2NDUwNTknLCAnc3luMjE2NDUwNjUnLCAnc3luMjE2NDUwNjcnLCAnc3luMjE2NDUwNjgnLCAnc3luMjE2NDUwNzEnLCAnc3luMjE2NDUwNzInLCAnc3luMjE2NDUwNzUnLCAnc3luMjE2NDUwNzgnLCAnc3luMjE2NDUwODAnLCAnc3luMjE2NDUwODEnLCAnc3luMjE2NDUwODYnLCAnc3luMjE2NDUwODcnLCAnc3luMjE2NDUwOTInLCAnc3luMjE2NDUwOTQnLCAnc3luMjE2NDUxMDAnLCAnc3luMjE2NDUxMTAnLCAnc3luMjE2NDUxMTInLCAnc3luMjE2NDUxMTgnLCAnc3luMjE2NDUxMTknLCAnc3luMjE2NDUxMjQnLCAnc3luMjE2NDUxMjUnLCAnc3luMjE2NDUxMjcnLCAnc3luMjE2NDUxMjknLCAnc3luMjE2NDUxMzInLCAnc3luMjE2NDUxMzQnLCAnc3luMjE2NDUxMzUnLCAnc3luMjE2NDUxMzcnLCAnc3luMjE2NDUxMzknLCAnc3luMjE2NDUxNDEnLCAnc3luMjE5MTc0ODQnLCAnc3luMjE5MTc0ODUnLCAnc3luMjE5MTc0ODYnLCAnc3luMjE5MTc0ODcnLCAnc3luMjE5MTc0ODgnLCAnc3luMjE5MTc0ODknLCAnc3luMjE5MTc0OTAnKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=)

**Comment by bswhite** [comment]
@jaeddy , I'm working on this. I have the missing projects. I don't know why they are missing from the merged table.

**Comment by bswhite** [comment]
@andrewelamb All of those are legitimate projects that should be in the merged projects table. I have included their descriptions and mapping to grants here. I needed to use fread to open this file in R because of some quoting in the description field.

[missing-project-descriptions.csv.txt](https://github.com/Sage-Bionetworks/csbc-pson-dcc/files/4685446/missing-project-descriptions.csv.txt)

**Comment by andrewelamb** [comment]
@bswhite These have all been added

**Comment by bswhite** [comment]
@andrewelamb , I don't believe the descriptions for the projects were added. Would you please add them in the merged projects table [here](https://www.synapse.org/#!Synapse:syn21868602/tables/) and any etl-related table?

I manually added the description for this project
Physical modeling and dynamics of tumor cell migration mechanics

**Comment by andrewelamb** [comment]
@bswhite 

There are descriptions for all these projects [here](https://www.synapse.org/#!Synapse:syn21868407/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxODY4NDA3IHdoZXJlIHByb2plY3RJZCBpbiAoJ3N5bjIxNjQ1MDEwJywgJ3N5bjIxNjQ1MDExJywgJ3N5bjIxNjQ1MDE2JywgJ3N5bjIxNjQ1MDE4JywgJ3N5bjIxNjQ1MDE5JywgJ3N5bjIxNjQ1MDIyJywgJ3N5bjIxNjQ1MDIzJywgJ3N5bjIxNjQ1MDI5JywgJ3N5bjIxNjQ1MDQwJywgJ3N5bjIxNjQ1MDQ1JywgJ3N5bjIxNjQ1MDU3JywgJ3N5bjIxNjQ1MDU5JywgJ3N5bjIxNjQ1MDY1JywgJ3N5bjIxNjQ1MDY3JywgJ3N5bjIxNjQ1MDY4JywgJ3N5bjIxNjQ1MDcxJywgJ3N5bjIxNjQ1MDcyJywgJ3N5bjIxNjQ1MDc1JywgJ3N5bjIxNjQ1MDc4JywgJ3N5bjIxNjQ1MDgwJywgJ3N5bjIxNjQ1MDgxJywgJ3N5bjIxNjQ1MDg2JywgJ3N5bjIxNjQ1MDg3JywgJ3N5bjIxNjQ1MDkyJywgJ3N5bjIxNjQ1MDk0JywgJ3N5bjIxNjQ1MTAwJywgJ3N5bjIxNjQ1MTEwJywgJ3N5bjIxNjQ1MTEyJywgJ3N5bjIxNjQ1MTE4JywgJ3N5bjIxNjQ1MTE5JywgJ3N5bjIxNjQ1MTI0JywgJ3N5bjIxNjQ1MTI1JywgJ3N5bjIxNjQ1MTI3JywgJ3N5bjIxNjQ1MTI5JywgJ3N5bjIxNjQ1MTMyJywgJ3N5bjIxNjQ1MTM0JywgJ3N5bjIxNjQ1MTM1JywgJ3N5bjIxNjQ1MTM3JywgJ3N5bjIxNjQ1MTM5JywgJ3N5bjIxNjQ1MTQxJywgJ3N5bjIxOTE3NDg0JywgJ3N5bjIxOTE3NDg1JywgJ3N5bjIxOTE3NDg2JywgJ3N5bjIxOTE3NDg3JywgJ3N5bjIxOTE3NDg4JywgJ3N5bjIxOTE3NDg5JywgJ3N5bjIxOTE3NDkwJykiLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9) but the [merged table](https://www.synapse.org/#!Synapse:syn21868602/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxODY4NjAyIHdoZXJlIHByb2plY3RJZCBpbiAoJ3N5bjIxNjQ1MDEwJywgJ3N5bjIxNjQ1MDExJywgJ3N5bjIxNjQ1MDE2JywgJ3N5bjIxNjQ1MDE4JywgJ3N5bjIxNjQ1MDE5JywgJ3N5bjIxNjQ1MDIyJywgJ3N5bjIxNjQ1MDIzJywgJ3N5bjIxNjQ1MDI5JywgJ3N5bjIxNjQ1MDQwJywgJ3N5bjIxNjQ1MDQ1JywgJ3N5bjIxNjQ1MDU3JywgJ3N5bjIxNjQ1MDU5JywgJ3N5bjIxNjQ1MDY1JywgJ3N5bjIxNjQ1MDY3JywgJ3N5bjIxNjQ1MDY4JywgJ3N5bjIxNjQ1MDcxJywgJ3N5bjIxNjQ1MDcyJywgJ3N5bjIxNjQ1MDc1JywgJ3N5bjIxNjQ1MDc4JywgJ3N5bjIxNjQ1MDgwJywgJ3N5bjIxNjQ1MDgxJywgJ3N5bjIxNjQ1MDg2JywgJ3N5bjIxNjQ1MDg3JywgJ3N5bjIxNjQ1MDkyJywgJ3N5bjIxNjQ1MDk0JywgJ3N5bjIxNjQ1MTAwJywgJ3N5bjIxNjQ1MTEwJywgJ3N5bjIxNjQ1MTEyJywgJ3N5bjIxNjQ1MTE4JywgJ3N5bjIxNjQ1MTE5JywgJ3N5bjIxNjQ1MTI0JywgJ3N5bjIxNjQ1MTI1JywgJ3N5bjIxNjQ1MTI3JywgJ3N5bjIxNjQ1MTI5JywgJ3N5bjIxNjQ1MTMyJywgJ3N5bjIxNjQ1MTM0JywgJ3N5bjIxNjQ1MTM1JywgJ3N5bjIxNjQ1MTM3JywgJ3N5bjIxNjQ1MTM5JywgJ3N5bjIxNjQ1MTQxJywgJ3N5bjIxOTE3NDg0JywgJ3N5bjIxOTE3NDg1JywgJ3N5bjIxOTE3NDg2JywgJ3N5bjIxOTE3NDg3JywgJ3N5bjIxOTE3NDg4JywgJ3N5bjIxOTE3NDg5JywgJ3N5bjIxOTE3NDkwJykiLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9) has only one of them. Is the merged table correct?
