### ISSUE TITLE
Publications missing from merged publication table

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#63]
These publications are missing from the merged publication table:

1] "syn21645279" "syn21645281" "syn21645603" "syn21648900" "syn21648910" "syn21648958" "syn21649079"
 [8] "syn21649080" "syn21681787" "syn21681888" "syn21682016"

**Comment by bswhite** [comment]
@andrewelamb OK, can you provide me a table with more information about them? Most importantly, what are their associated grantIds, grantNumbers, and grantNames? I wonder if I manually removed the associated grant. If you have the publication title and pubmed URL, that would also be helpful.

**Comment by andrewelamb** [comment]
@bswhite 

Here are the [publications themselves](https://www.synapse.org/#!Synapse:syn21650536/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjUwNTM2IFdIRVJFIGlkIElOICgnc3luMjE2NDUyNzknLCAnc3luMjE2NDUyODEnLCAnc3luMjE2NDU2MDMnLCAnc3luMjE2NDg5MDAnLCAnc3luMjE2NDg5MTAnLCAnc3luMjE2NDg5NTgnLCAnc3luMjE2NDkwNzknLCAnc3luMjE2NDkwODAnLCAnc3luMjE2ODE3ODcnLCAnc3luMjE2ODE4ODgnLCAnc3luMjE2ODIwMTYnKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=)

It looks like [these](https://www.synapse.org/#!Synapse:syn21682660/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxNjgyNjYwIFdIRVJFIHB1YmxpY2F0aW9uSWQgSU4gKCdzeW4yMTY0NTI3OScsICdzeW4yMTY0NTI4MScsICdzeW4yMTY0NTYwMycsICdzeW4yMTY0ODkwMCcsICdzeW4yMTY0ODkxMCcsICdzeW4yMTY0ODk1OCcsICdzeW4yMTY0OTA3OScsICdzeW4yMTY0OTA4MCcsICdzeW4yMTY4MTc4NycsICdzeW4yMTY4MTg4OCcsICdzeW4yMTY4MjAxNicpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==) don't have grant ids associated with them(which is why they may be excluded from the merged table

**Comment by bswhite** [comment]
@andrewelamb 

But some of these _do_ have grantId annotations (even if they aren't in that grant id table).

These have no annotations at all:
syn21682016
syn21681888
syn21681787

These have NA grantIds:
syn21649080
syn21649079

These have grantId = 7349770
syn21648958
syn21648900
syn21645281
syn21645279

These have grantId = 9773346
syn21648910

These have grantId = 9772917
syn21645603

How do we get more information about these grantIds?

**Comment by bswhite** [comment]
I see, the grantIds are just synapse IDs without the "syn" prefix.

The three grantIds above and legitimate and are at least in the live/merged grants table.

They are:
syn7349770
Center on the Physics of Cancer Metabolism

syn9773346
Systems Analysis of Epigenomic Architecture in Cancer Progression

syn9772917
Embryonal Brain Tumor Networks

**Comment by andrewelamb** [comment]
@bswhite @jaeddy 

I've added the grant ids to the above listed publications.

Is there anything to be done with these publications then:

These have no annotations at all:
syn21682016
syn21681888
syn21681787

These have NA grantIds:
syn21649080
syn21649079

Delete them? Leave them in(the publications table, not the merged portal publication table)?

**Comment by bswhite** [comment]
Google'ing the publication title and finding the funding source on pubmed tells me that:

syn21649080 should be assigned to CA195469

syn21649079 should be assigned to CA210173

Can you tell me anything about these 3 publications without any annotations? How did they end up in your table? Without some information I can't track them down
syn21682016
syn21681888
syn21681787

**Comment by jaeddy** [comment]
@bswhite here are the PubMed records for those 3 publications:

| Entity | PubMed |
| --- | --- |
| syn21682016 | https://pubmed.ncbi.nlm.nih.gov/31917525 |
| syn21681888 | https://pubmed.ncbi.nlm.nih.gov/31485072 |
| syn21681787 | https://pubmed.ncbi.nlm.nih.gov/31161239 |

I'm guessing the annotations might have gotten "lost in translation" when trying to save the View to Synapse. We might be able to trace the info back to [this table](https://www.synapse.org/#!Synapse:syn10923842/tables/).

**Comment by andrewelamb** [comment]
I added grantIds for the two @bswhite  mentioned.

**Comment by aclayton555** [comment]
@jaeddy this has been resolved but I cannot figure out how to close this issue (I might not have the correct permission on this repo??? I suck at using github???). Anyway, could you kind please close this.
Resolution: https://sagebionetworks.jira.com/browse/CPO-82

**Comment by jaeddy** [comment]
Thanks! I added you to the [CSBC/PS-ON Admin team](https://github.com/orgs/Sage-Bionetworks/teams/csbc-pson-admin/members), so you'll have admin permissions on this repo and some other related ones in the future.
