### ISSUE TITLE
datasets with duplicate grants

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#68]
These [datasets](https://www.synapse.org/#!Synapse:syn22038800/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIyMDM4ODAwIHdoZXJlIGRhdGFzZXRJZCBpbiAoJ3N5bjIxODg5NzcwJywgJ3N5bjIxODg5NzcwJykiLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9) have duplicated grants. I can delete the extras if that's ok.

**Comment by bswhite** [comment]
@andrewelamb , yes please delete the duplicates.
