### ISSUE TITLE
aggregate (as opposed to per-sample) GEO files

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#72]
Some GEO datasets, such as this one
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE107559
seem to only have aggregate files (e.g., expression matrices across all samples), as opposed to per-sample files. get-geo-annotations.R, which was used to link many of these files, does not pick up those aggregate files. 

How do we find them? Need to go back and find datasets with those aggregate files and link them.

**Comment by vpchung** [comment]
Closing due to legacy. Will re-open in mc2-center-dcc or pubmed-crawler if needed.
