### ISSUE TITLE
blank publications are being rendered on portal

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#79]
Blank publications are now being rendered on the portal (see attached screenshot), whereas previously they would be dropped from the cards (the desired behavior). I imagine this is happening because publications were changed to STRING_LIST and the portal is not detecting them as empty.

Here is the corresponding entry in the datasets table:
https://www.synapse.org/#!Synapse:syn21897968/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxODk3OTY4IHdoZXJlIGRhdGFzZXROYW1lID0gJ0NlbGwgU3RpZmZuZXNzIGFuZCBNaWdyYXRpb24gTWljcm9zY29weSciLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9
<img width="1206" alt="umn-blank-publication" src="https://user-images.githubusercontent.com/5123034/82960527-9fd5da00-9f6f-11ea-8b49-cf354a2cfe16.png">

**Comment by jaeddy** [comment]
Yup — I let @leem42 and he opened a Jira ticket: https://sagebionetworks.jira.com/browse/PORTALS-1370

**Comment by jaeddy** [comment]
Fixed by @leem42
