### ISSUE TITLE
Consolidate any code related to NCBI/PubMed crawling and text mining

### ISSUE THREAD

**Issue by jaeddy** [mc2-center/csbc-pson-dcc#8]
I believe @Tumpsh and @bswhite have been working on some scripts/code to annotate CSBC/PS-ON publications based on some combination of text mining, API requests, etc. We should make sure these are all captured and version-controlled in GitHub (either in this repo or another).

**Comment by bswhite** [comment]
@vpchung and @milen-sage can you tell us where the pubmed crawler is?

**Comment by vpchung** [comment]
I used [this command](https://github.com/Sage-Bionetworks/syndccutils/blob/pubmed/python/syndccutils/__main__.py) to find and annotate the publications of a given grant number.

I am currently refactoring it and adding some features to it, e.g. adding a check that we were able to retrieve publications for each queried grant.

**Comment by jaeddy** [comment]
Thanks, @vpchung! Let me know when you finish making changes to the script. I'll probably migrate the code to this repo for the near term — it was always a bit of an outlier with the **syndccutils** R package anyway.

**Comment by vpchung** [comment]
@jaeddy would it be easier if I refactor the code into this repo?

**Comment by jaeddy** [comment]
@vpchung — sure! That works for me. :)

**Comment by jaeddy** [comment]
@Tumpsh — looping you in on this thread as well.
