### ISSUE TITLE
Merged grant table NA values

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#81]
These [grants](https://www.synapse.org/#!Synapse:syn21918972/tables/query/eyJzcWwiOiJTRUxFQ1QgZ3JhbnRJZCwgaW5zdGl0dXRpb25JZCwgaW5zdGl0dXRpb24gRlJPTSBzeW4yMTkxODk3MiB3aGVyZSBncmFudElkIGluICgnc3luMjA2NzM1NDUnLCdzeW4yMTYxOTA3MCcsJ3N5bjIxNjE5NDMyJywnc3luMjE2MTk3NTknKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=) have no instituionIds, but have institutions. They have no entries in the [association table](https://www.synapse.org/#!Synapse:syn21905912/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxOTA1OTEyIHdoZXJlIGdyYW50SWQgaW4gKCdzeW4yMDY3MzU0NScsJ3N5bjIxNjE5MDcwJywnc3luMjE2MTk0MzInLCdzeW4yMTYxOTc1OScpIiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAiaXNDb25zaXN0ZW50Ijp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==) So it seems we should set institution to NA for these as well. If these were manually added the institution ids should have been added(not the name) and reverse-etl will take care of it.

These [grants](https://www.synapse.org/#!Synapse:syn21918972/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxOTE4OTcyIHdoZXJlIGdyYW50SWQgaW4gKCdzeW4yMDY3MzU0NScsJ3N5bjIxNjE5MDcwJywnc3luMjE2MTkwODInLCdzeW4yMTYxOTQzMicsJ3N5bjIxNjE5NzU5Jywnc3luMjE2MTk3NzMnLCdzeW4yMTYxOTg1MycsJ3N5bjcwODA3MTQnLCdzeW45Nzc0NzgzJywnc3luOTc3NTY1MScsJ3N5bjk3NzU2ODknKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=), have investigators but these relationships aren't in the [association table](https://www.synapse.org/#!Synapse:syn21905932/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIxOTA1OTMyIHdoZXJlIGdyYW50SWQgaW4gKCdzeW4yMDY3MzU0NScsJ3N5bjIxNjE5MDcwJywnc3luMjE2MTkwODInLCdzeW4yMTYxOTQzMicsJ3N5bjIxNjE5NzU5Jywnc3luMjE2MTk3NzMnLCdzeW4yMTYxOTg1MycsJ3N5bjcwODA3MTQnLCdzeW45Nzc0NzgzJywnc3luOTc3NTY1MScsJ3N5bjk3NzU2ODknKSIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=) . There is no investigator id column so these can't be added manually .

**Comment by jaeddy** [comment]
Looks like an issue with my code (somewhere), not the annotations. I need to make some updates to institution names anyway, so I'll take a look at this.

**Comment by jaeddy** [comment]
@andrewelamb the issue with institutions should be fixed (I created new entities for the 4 institutions that didn't have IDs, updated the merged table, and updated the association table).

For the investigators, you should just be able to use `separate_rows` to split people into multiple rows per `grantId`, then tack any new rows onto the end of the association table.

**Comment by andrewelamb** [comment]
@jaeddy For some reason I was thinking investigators(persons) where entities that had a synapse ID.

The changes fixed everything!
