### ISSUE TITLE
Tool grant numbers incorrect

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#82]
These [tools](https://www.synapse.org/#!Synapse:syn21930566/tables/query/eyJzcWwiOiJTRUxFQ1QgdG9vbElkLCBncmFudElkLCBncmFudCBGUk9NIHN5bjIxOTMwNTY2IHdoZXJlIHRvb2xJZCBpbiAoJ3N5bjIxNjQ1MTk1JywgJ3N5bjIxNjQ1MTk2JykiLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9) have an incorrect grant number. The grant number for this grantId should be CA215845. I change this if that's ok.

**Comment by jaeddy** [comment]
Yeah — that'd be great. This is the same change I made for the publications table.
