### ISSUE TITLE
New CSBC U01s to be added to portal

### ISSUE THREAD

**Issue by jkcinelli** [mc2-center/csbc-pson-dcc#84]
We have 3 new U01s that we should add to the portal prior to launch. Attaching a spreadsheet with title, grant number, summary and MPIs. Please let me know what else you need. 
[new CSBC U01s.xlsx](https://github.com/Sage-Bionetworks/csbc-pson-dcc/files/4698985/new.CSBC.U01s.xlsx)

PS- this is my first time posting an issue, so please let me know if I'm doing it incorrectly...

**Comment by vpchung** [comment]
@jkcinelli I will start on adding these today!

**Comment by vpchung** [comment]
@jkcinelli I have added the new CSBC grants; their projects are located here:

- [U01 CA243072](https://www.synapse.org/#!Synapse:syn22117059/wiki/)
- [U01 CA243075](https://www.synapse.org/#!Synapse:syn22117060/wiki/)
- [U01 CA238728](https://www.synapse.org/#!Synapse:syn22092596/wiki/603331)

I'm not sure if this is important for the presentation but all three are currently missing `theme` annotations. Will it be possible for these to be provided to us? The themes we are using are:

- Microenvironment
- Heterogeneity
- Metastasis
- Evolution
- Drug Resistance/Sensitivity
- Metabolism
- Tumor-Immune
- Epigenetics

Thank you!

**Comment by jkcinelli** [comment]
Theme annotations are as follows:

CA243072- drug resistance/sensitivity
CA243075-drug resistance/sensitivity
CA238728-microenvironment/tumor-immune

**Comment by vpchung** [comment]
Thanks, @jkcinelli ! These grants are ready to go for tomorrow.
