### ISSUE TITLE
Dataset/Publication relationship confusion

### ISSUE THREAD

**Issue by andrewelamb** [mc2-center/csbc-pson-dcc#85]
The relationship between datasets and publications is confusing.

One one hand both datasets and and publications belong to a grant. So to get all the dataset information for a publication one could get its grants, and then get the publications associated with the grant. This is true for doing the reverse as well. Both the merged tables do so.

This is fine so far as long as the publications columns in the dataset table, and the dataset columns in the publication table aren't changed(the user would need to change the grant ids). However the portal etl script uses [this table](https://www.synapse.org/#!Synapse:syn21895676/tables/) to mange the relationships between the two. This is hard to resolve from a reverse etl standpoint because now the order things are updated matters. If the relationship between datasets and publications get changed in one table, but not the other, which is correct?

It seems like the dataset_publication table is not needed and complicates things, especially from the reverse etl prespective.

**Comment by jaeddy** [comment]
@andrewelamb when I was originally creating the normalized tables, I had publications pointing to datasets and datasets pointing to publications — but they were in two separate tables and weren't necessarily consistent. I'm working on a validation check to assess the bi-directional accuracy (and completeness) of all dataset <-> publication links. Once we get that sorted out, we can update the `dataset_publication` table and it should be useful again.

I think the path I would expect moving forward is grant -> publication -> BioProject -> dataset(s) -> samples/files. However, we don't have this pipeline working yet and are trying to retrospectively resolve annotations from a variety of sources and approaches.

**Comment by bswhite** [comment]
@jaeddy that certainly seems like the most common path. Is it far to assume the portal will not demand this path, though? Like in the rare exception when we get a contributed dataset that is not associated with a BioProject (or publication).

**Comment by vpchung** [comment]
Closing, due to legacy.
