### ISSUE TITLE
Overview of existing annotation scripts

### ISSUE THREAD

**Issue by bswhite** [mc2-center/csbc-pson-dcc#89]
The below is an attempt to describe the components we currently have for automated annotation (e.g., pubmed scraping) as a necessary precursor to better binding them together into one pipeline. I don't think the etl stuff belongs here, but I could be wrong. @vpchung and @jaeddy please edit/add things I'm missing.

Publication annotation pipeline:

1. [`pubmed_crawler.py`](https://github.com/Sage-Bionetworks/csbc-pson-dcc/blob/master/python/pubmed_crawler.py) queries pubmed for publications associated with grants listed in a synapse table and returns information for each publication including "Journal", "Publication Year", "Title", "Authors", "Grant", "SRX", "SRX Link", "SRP", "SRP Link", "dbGaP", "dbGaP Link", "Keywords". This is currently maintained and last updated by Verena. This is the starting point for our publication-based annotating and, insofar as GEO/SRA/dbGaP datasets are found from their associated publications, for data annotation as well.

2. [`get_disease_annotation.py`](https://github.com/Sage-Bionetworks/csbc-pson-dcc/blob/master/manifest-scripts/code/get_disease_annotation.py) outputs disease annotations for each pubmed id. This was written by Thomas Corey. It involves extracting MeSH terms, translating them to MeSH concept IDs (I believe), and then translating those to our standard ontology (using a provided mapping table). This perhaps should be separated into multiple scripts (e.g., extracting MeSH vs mapping to our ontology).

3. Assigning tissue based on disease. The tumorType of our controlled vocabulary spreadsheet [CSBC/PS-ON Controlled Vocabulary (v1)](https://docs.google.com/spreadsheets/d/1_Ho4tjgdxSHo19qFhlLJhZAyQSPPDW-W8JN910GizDs/edit#gid=0) has a column specifying the associated tissue of each tumorType. I don't know if we/I had a specialized script to do so, but assigning tissues based on disease is a simple matter of merging the disease/tumorType column from (2) to the tissue column here.

Grant/project annotation pipeline.

1. [`projects_and_cores.py`](https://github.com/Sage-Bionetworks/csbc-pson-dcc/blob/master/python/projects_and_cores.py) scrapes Synapse Wiki pages to extract Grant descriptions and Project/Core descriptions _assuming_ highly stylized Wiki organizations. Written by Verena.

**Comment by vpchung** [comment]
Thanks @bswhite!

I have two additional Python scripts that I've been meaning to add:

- `get_geo_design.py` - writes a TSV file of GEO series designs 
IIRC, this has been refactored into R by Brian so this _probably_ doesn't need to be added

- `add_grants.py` - creates Wiki pages for new grants, and adds their metadata into the "Portal - Grants Merged" table

**Comment by vpchung** [comment]
Ah! Also, @jaybee84 has also created an R script that iterates through a Google sheet of dataset annotations and adds them to the appropriate Synapse entity, as well as creates a metadata FileView for each dataset within its given project.

My plan is to refactor this script so that it can be used with any CSV/Googlesheet given.

**Comment by jaeddy** [comment]
Thanks, @bswhite for kickstarting this discussion. @vpchung, @jaybee84 - if you haven't already, can you create a PR for any additional code/scripts you've written? I think it'll be easier to organize all the different pieces when they're in the same branch.

**Comment by vpchung** [comment]
Sure thing -- just going to need to add some comments first :)

Also, would you like me to start adding unit tests for the scripts?

**Comment by jaeddy** [comment]
@vpchung if you want to start brainstorming/defining test cases, that'd be awesome. I'd say hold off on writing actual tests yet until we get everything consolidated (I'm expecting there will be some redundancy).

**Comment by bswhite** [comment]
I've added a bit more detail describing how pubmed_crawler.py and get_disease_annotation.py are used to populate publication fields in the Google sheet [here](https://docs.google.com/spreadsheets/d/1lnK8MIZIpT1oSsVA1r2pS9kgqnsdCR66G8c4snQ1bTQ/edit?usp=sharing). This sheet includes the original source of the annotation fields (e.g., PubMed, Entrez, etc), the script that derives it, and the field's name in the portal.

Note that get_disease_annotation.py pulls MeSH disease terms from PubMed and then translates these to the corresponding UMLS (Unified Medical Language System) Metathesaurus Concept Unique Ids (CUIs). MeSH terms (and other non-MeSH ids) are mapped to CUIs, where CUIs are defined like so (from [here](https://www.nlm.nih.gov/research/umls/new_users/glossary.html#c)):

Concept - The fundamental unit of meaning in the Metathesaurus. A concept represents a single meaning and contains all atoms from any source that express that meaning in any way, whether formal or casual, verbose or abbreviated. All of the atoms within a concept are synonymous. Each concept is assigned at least one semantic type.  Every concept is assigned a Concept Unique Identifier, or CUI, which uniquely identifies that single meaning.

**Comment by vpchung** [comment]
Closing, as pubmed crawler has been documented.
